project_id = "jgpffcjktwsohfyljtsg"

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.send-booking-confirmation]
verify_jwt = true

[functions.send-promotional-email]
verify_jwt = true